/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    /*id INT SERIAL PRIMARY KEY*/
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(255),
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL(6, 2),
    PRIMARY KEY(id)
);
